# Generated by Django 3.0.3 on 2020-06-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppThree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
